language: php

php:
    - "5.5"
    - "5.3"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install
    - npm install

script:
    - phpunit
    - grunt test --verbose --force
    - ./vendor/wp-cli/wp-cli/bin/wp --require=./vendor/wp-codeception/wp-codeception.php codeception bootstrap
    - ./vendor/wp-cli/wp-cli/bin/wp --require=./vendor/wp-codeception/wp-codeception.php selenium start
    - ./vendor/wp-cli/wp-cli/bin/wp --require=./vendor/wp-codeception/wp-codeception.php codeception run